#spring:
#  jms:
#    jndi-name: DEMO_CF

ibm:
  mq:
    user: admin
    password: passw0rd
    channel: DEV.ADMIN.SVRCONN
    queueManager: QM1
    connName: localhost(1414)
#    additional-properties:
#      XMSC_WMQ_SEND_CHECK_COUNT: 10

server:
  port: 8081